#Importing Dependencies

In [1]:
import pandas as pd
import numpy as np


In [2]:
df = pd.read_csv("/content/drive/MyDrive/project/Faringham-Disease-Prediction/framingham.csv")

In [3]:
df.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

#Data Preprocessing

In [4]:
df.columns

Index(['male', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds',
       'prevalentStroke', 'prevalentHyp', 'diabetes', 'totChol', 'sysBP',
       'diaBP', 'BMI', 'heartRate', 'glucose', 'TenYearCHD'],
      dtype='object')

In [69]:
df.isnull().sum()

male                 0
age                  0
education            0
currentSmoker        0
cigsPerDay           0
BPMeds               0
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol              0
sysBP                0
diaBP                0
BMI                  0
heartRate            0
glucose            388
TenYearCHD           0
dtype: int64

In [73]:
df.dtypes

male                 int64
age                  int64
education          float64
currentSmoker        int64
cigsPerDay         float64
BPMeds             float64
prevalentStroke      int64
prevalentHyp         int64
diabetes             int64
totChol            float64
sysBP              float64
diaBP              float64
BMI                float64
heartRate          float64
glucose            float64
TenYearCHD           int64
dtype: object

In [74]:
df['TenYearCHD'].unique()

array([0, 1])

In [35]:
df['cigsPerDay'].unique()

array([ 0., 20., 30., 23., 15.,  9., 10.,  5., 35., 43.,  1., 40.,  3.,
        2., nan, 12.,  4., 18., 25., 60., 14., 45.,  8., 50., 13., 11.,
        7.,  6., 38., 29., 17., 16., 19., 70.])

In [40]:
df['BPMeds'].unique()

array([ 0.,  1., nan])

In [51]:
df['totChol'].nunique()

249

In [48]:
df['totChol'].value_counts()

240.0    85
220.0    70
260.0    62
210.0    61
232.0    59
         ..
392.0     1
405.0     1
359.0     1
398.0     1
119.0     1
Name: totChol, Length: 248, dtype: int64

In [50]:
df['totChol'].value_counts()

240.0    85
220.0    70
260.0    62
210.0    61
232.0    59
         ..
126.0     1
365.0     1
362.0     1
405.0     1
119.0     1
Name: totChol, Length: 249, dtype: int64

In [67]:
df['BMI'].value_counts()

25.800801    19
22.910000    18
22.540000    18
23.480000    18
22.190000    18
             ..
34.130000     1
23.210000     1
29.130000     1
19.870000     1
20.910000     1
Name: BMI, Length: 1365, dtype: int64

In [66]:
df['heartRate'].value_counts()

75.0     563
80.0     385
70.0     305
60.0     231
85.0     228
        ... 
47.0       1
130.0      1
140.0      1
51.0       1
46.0       1
Name: heartRate, Length: 73, dtype: int64

In [71]:
df['glucose'].value_counts()

75.0     193
77.0     167
73.0     156
80.0     153
70.0     152
        ... 
386.0      1
155.0      1
147.0      1
205.0      1
260.0      1
Name: glucose, Length: 143, dtype: int64

In [72]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy = 'mean')
df['education'] = si.fit_transform(df['education'].values.reshape(-1,1))
df['cigsPerDay'] = si.fit_transform(df['cigsPerDay'].values.reshape(-1,1))
df['BMI'] = si.fit_transform(df['BMI'].values.reshape(-1,1))

si2 = SimpleImputer(strategy = 'most_frequent')
df['BPMeds'] = si2.fit_transform(df['BPMeds'].values.reshape(-1,1))
df['heartRate'] = si2.fit_transform(df['heartRate'].values.reshape(-1,1))

si3 = SimpleImputer(strategy = 'constant')
df['totChol'] = si3.fit_transform(df['totChol'].values.reshape(-1,1))
df['glucose'] = si3.fit_transform(df['glucose'].values.reshape(-1,1))

In [75]:
df.isnull().sum()

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [17]:
df.describe()

male          age    education  currentSmoker   cigsPerDay  \
count  4240.000000  4240.000000  4135.000000    4240.000000  4211.000000   
mean      0.429245    49.580189     1.979444       0.494104     9.005937   
std       0.495027     8.572942     1.019791       0.500024    11.922462   
min       0.000000    32.000000     1.000000       0.000000     0.000000   
25%       0.000000    42.000000     1.000000       0.000000     0.000000   
50%       0.000000    49.000000     2.000000       0.000000     0.000000   
75%       1.000000    56.000000     3.000000       1.000000    20.000000   
max       1.000000    70.000000     4.000000       1.000000    70.000000   

            BPMeds  prevalentStroke  prevalentHyp     diabetes      totChol  \
count  4187.000000      4240.000000   4240.000000  4240.000000  4190.000000   
mean      0.029615         0.005896      0.310613     0.025708   236.699523   
std       0.169544         0.076569      0.462799     0.158280    44.591284   
min       0.000000         0.000000      0.000000     0.000000   107.000000   
25%       0.000000         0.000000      0.000000     0.000000   206.000000   
50%       0.000000         0.000000      0.000000     0.000000   234.000000   
75%       0.000000         0.000000      1.000000     0.000000   263.000000   
max       1.000000         1.000000      1.000000     1.000000   696.000000   

             sysBP        diaBP          BMI    heartRate      glucose  \
count  4240.000000  4240.000000  4221.000000  4239.000000  3852.000000   
mean    132.354599    82.897759    25.800801    75.878981    81.963655   
std      22.033300    11.910394     4.079840    12.025348    23.954335   
min      83.500000    48.000000    15.540000    44.000000    40.000000   
25%     117.000000    75.000000    23.070000    68.000000    71.000000   
50%     128.000000    82.000000    25.400000    75.000000    78.000000   
75%     144.000000    90.000000    28.040000    83.000000    87.000000   
max     295.000000   142.500000    56.800000   143.000000   394.000000   

        TenYearCHD  
count  4240.000000  
mean      0.151887  
std       0.358953  
min       0.000000  
25%       0.000000  
50%       0.000000  
75%       0.000000  
max       1.000000

#Splitting into Testing and Training

In [76]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1] 

In [77]:
from sklearn.model_selection import train_test_split

In [78]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.2, random_state = 42)

In [79]:
len(X_train)

3392

#Fitting The Decision Tree Model

In [90]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(criterion='entropy', random_state = 50)
model.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=50)

In [91]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = model.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[619, 106],
       [ 98,  25]])

In [92]:
print('Accuracy Score : ', accuracy_score(y_test, y_pred))

Accuracy Score :  0.7594339622641509


#Fitting The Naive bayes Model

In [93]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [94]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = model.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[682,  43],
       [102,  21]])

In [95]:
print('Accuracy Score : ', accuracy_score(y_test, y_pred))

Accuracy Score :  0.8290094339622641


#Fitting The k-Nearest Neighbor

In [103]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors = 10)
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [104]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = model.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[717,   8],
       [120,   3]])

In [105]:
print('Accuracy Score : ', accuracy_score(y_test, y_pred))

Accuracy Score :  0.8490566037735849


#Fitting The Support Vector Machine Model

In [106]:
from sklearn.svm import SVC

model = SVC()
model.fit(X_train, y_train)

SVC()

In [107]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = model.predict(X_test)

confusion_matrix(y_test, y_pred)

array([[724,   1],
       [121,   2]])

In [108]:
print('Accuracy Score : ', accuracy_score(y_test, y_pred))

Accuracy Score :  0.8561320754716981
